{{- with .Values.mounts }}
  {{- with .secretFiles }}
    {{- if .enabled }}
      {{- range $sec := .list }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.applicationName }}-{{ $sec.name }}-secretfiles
  labels:
    app: {{ $.Values.applicationName }}
type: Opaque
data:

{{- /* if subPath is empty, include all files from fileList */}}
{{- if not $sec.subPath }}
  {{- range $key, $value := $sec.fileList }}
    {{- if $sec.binary }}
    {{ tpl $key $ }} : {{ $.Files.Get (tpl $value $) | b64enc }}
    {{- else }}
    {{ tpl $key $ }} : {{ tpl ($.Files.Get (tpl $value $)) $ | b64enc }}
    {{- end }}
  {{- end }}
{{- /* if subPath is set, render only the matching file */}}
{{- else }}
  {{- range $key, $value := $sec.fileList }}
    {{- if eq $sec.subPath $key }}
      {{- if $sec.binary }}
      {{ tpl $key $ }} : {{ $.Files.Get (tpl $value $) | b64enc }}
      {{- else }}
      {{ tpl $key $ }} : {{ tpl ($.Files.Get (tpl $value $)) $ | b64enc }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
---
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
